apiVersion: apps/v1
kind: Deployment
metadata:
    name: imgproc-client
spec:
    replicas: 1
    selector:
        matchLabels:
            app: imageProcessing
            tier: client
    template:
        metadata:
            labels:
                app: imageProcessing
                tier: client
        spec:          
            containers:
            - name: imgproc-client
              image: wangso/imgproc-client:V2
              imagePullPolicy: Always
              env:
                - name: server
                  value: Your-Unique-Host-Name.nrp-nautilus.io
              resources:
                limits:
                  memory: 2000Mi
                  cpu: 2
                requests:
                  memory: 1000Mi
                  cpu: 1
              volumeMounts:
              - mountPath: /ImageProcessingWebServices/output/client
                name: myvolume
            volumes:
            - name: myvolume
              persistentVolumeClaim:
                claimName: Your-Unique-Volume-Name
            restartPolicy: Always

      
