apiVersion: apps/v1
kind: Deployment
metadata:
    name: imgproc-client
spec:
    replicas: 1
    selector:
        matchLabels:
            app: imageProcessing
            tier: client
    template:
        metadata:
            labels:
                app: imageProcessing
                tier: client
        spec:          
            containers:
            - name: imgproc-client
              image: wangso/imgproc-client:V2
              imagePullPolicy: Always
              env:
                - name: server
                  value: "Your-LoadBancer-Name"
            restartPolicy: Always

      
