apiVersion: v1
kind: Pod
metadata:
  name: pvc-access-pod
spec:
  containers:
  - name: pvc-access-pod
    image: ubuntu:20.04
    command: ["/bin/bash", "-c"]
    args: ["mkdir /data; sleep 1000"]
    imagePullPolicy: Always
    resources:
        limits:
          memory: 200Mi
          cpu: 2
        requests:
          memory: 100Mi
          cpu: 1
    volumeMounts:
    - mountPath: /data
      name: myvolume
  volumes:
  - name: myvolume
    persistentVolumeClaim:
      claimName: Your-Unique-Volume-Name  
  restartPolicy: Always
