apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgproc-server
  labels: 
    app: imageProcessing
    tier: server
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: imageProcessing
      tier: server
  template:
    metadata:
      labels:
        app: imageProcessing
        tier: server
    spec:
      containers:
      - name: imgproc-server
        image: wangso/imgproc-server:V2
        imagePullPolicy: Always
        env:
          - name: server
            value: "Your-LoadBancer-Name"
        ports:
          - containerPort: 5000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: LoadBalancer
  selector:
    app: imageProcessing
    tier: server
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
